print("exception handling in python")
a=[20,30,50,100]
try:
    print(5/0)
except IndexError:
    print("exception occured")
except ZeroDivisionError:
    print("zero division error")
except:
    print("exception")
else:
    print("no exception occured")
finally:
    print("this is finally block ")
print("end!!")



print("exception handling in python")
a=[20,30,50,100]
try:
    print(a[7])
except IndexError:
    print("exception occured")
except ZeroDivisionError:
    print("zero division error")
except:
    print("exception")
else:
    print("no exception occured")
finally:
    print("this is finally block ")
print("end!!")


print("exception handling in python")
a=[20,30,50,100]
j=20
try:
    print(y)
except IndexError:
    print("exception occured")
except ZeroDivisionError:
    print("zero division error")
except NameError:
    print("name error")
except:
    print("exception")
else:
    print("no exception occured")
finally:
    print("this is finally block ")
print("end!!")

