print("exception handling in python")
try:
    a=4/0
except:
    print("exception occured")
else:
    print("no exception occured")
finally:
    print("this is finally block ")
print("end!!")


print("exception handling in python")
a=[10,30,40,60]
try:
    print(a[0])
except:
    print("exception occured")
else:
    print("no exception occured")
finally:
    print("this is finally block ")
print("end!!")


print("exception handling in python")
j=80
try:
    print(f)
except:
    print("exception occured")
else:
    print("no exception occured")
try:
    print(k)
except:
    print("exception")
else:
    print("not occured")
finally:
    print("this is finally block ")
print("end!!")
